### ISSUE TITLE
Implement feedback request

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#26]
(a) Front Page
- [x] Footer: verify its consistency (Portal)
- [ ] Improve a workflow image that describes the tool (AppSci)
- [x] EarthData signup link:  
   - both a login and create new account button would take the end user to the same Earthdata Login page 

(b) Selection Page
- [x] Use bread crumbs (instead of tab) for selection

**Comment by jbyrne6** [comment]
- A footer is there but more work needs to be done to make it look like the standard PO.DAAC footer
- will work with AppSci team on workflow image in the same ticket as adding to the About page
- I think there should only be one button for the EarthData login/sign up since it directs to the same EarthData Login page
- bread crumbs are not implemented yet. Will be started next sprint
